### ISSUE TITLE
calling the "label cost" function during optimizing ?

### ISSUE THREAD

**Issue by DemoGit4LIANG** [Borda/pyGCO#11]
Does this py wrapper call the "label cost" function during optimizing ?

**Comment by Borda** [comment]
Could you please elaborate more on what you mean by calling "label cost". Thx

**Comment by DemoGit4LIANG** [comment]
> Could you please elaborate more on what you mean by calling "label cost". Thx

Of course. The gco3.0 said it supports "label cost" in α-expansion during multi-label optimizing and prodvides relevent APIs (see http://mouse.cs.uwaterloo.ca/code/). I just want to know can I use this function via your py wrapper ? THX

**Comment by Borda** [comment]
OK, I see the `LabelCost` variable in the Cpp code [gco_source/GCoptimization.cpp](https://github.com/Borda/pyGCO/blob/master/gco_source/GCoptimization.cpp) as a part of several functions... :(there is no cpp example with using it)
Unfortunaty, these functions are not wrapped to python yet. So any help, an extension is welcome ;)

**Comment by DemoGit4LIANG** [comment]
> OK, I see the `LabelCost` variable in the Cpp code [gco_source/GCoptimization.cpp](https://github.com/Borda/pyGCO/blob/master/gco_source/GCoptimization.cpp) as a part of several functions... :(there is no cpp example with using it)
> Unfortunaty, these functions are not wrapped to python yet. So any help, an extension is welcome ;)

I see the py wrapper call the compute_energy() function in the **gco_source/GCoptimization.cpp** and the compute_energy() function invokes giveLabelEnergy(). So may be it has included the label cost factors ? Any way, thanks a lot !

**Comment by Borda** [comment]
@DemoGit4LIANG shall we close it then?
