### ISSUE TITLE
running `test_examples.py` fails

### ISSUE THREAD

**Issue by WakeWang1996** [Borda/pyGCO#12]
@Borda When I ran "python test_example.py", I met this error:
```
Traceback (most recent call last):
  File "test_examples.py", line 9, in <module>
    import gco
  File "/home/wang/exprience/texture/pyGCO-master/gco/__init__.py", line 10, in <module>
    from gco.pygco import *
  File "/home/wang/exprience/texture/pyGCO-master/gco/pygco.py", line 6, in <module>
    from .cgco import _cgco, _SMOOTH_COST_FN
  File "/home/wang/exprience/texture/pyGCO-master/gco/cgco.py", line 12, in <module>
    assert len(LIST_LIBGCO) > 0, 'nothing found: %s' % repr(LIST_LIBGCO)
AssertionError: nothing found: []
```
Could you tell me what make this happened? Thank you!

**Comment by Borda** [comment]
Hello, could you please be more specific with your OS and libraries version you are using?
In particular, you should be able to reproduce all results following instructions in [.travis.yml](https://github.com/Borda/pyGCO/blob/master/.travis.yml)
```
python setup.py install
python test_examples.py
```

**Comment by WakeWang1996** [comment]
@Borda Hello! I have solved my problem, I changed the code about the path of libcgco and now it worked. This is my carelessness, but thank you all the same!

**Comment by lyrgwlr** [comment]
@WakeWang1996 
Hi,  I met the same problem like you.
Can you tell me how to change the code about the path of libcgco specifically?
Thanks!

**Comment by WakeWang1996** [comment]
I changed the code in cgco.py, line 8. To my own path that contains libcgco.so. 



---Original---
